name: Deploy

on:
  push:
    branches:
      - main

env:
  GIT_HUB_KEY: ${{ secrets.GIT_HUB_KEY }}

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set environment variable
      run: echo "GIT_HUB_KEY=$GIT_HUB_KEY" >> $GITHUB_ENV
