name: Deploy

on:
  push:
    branches:
      - main

env:
  API_KEY: ${{ secrets.GIT_HUB_KEY }}

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Deploy to production
      run: |
        echo "API Key: $API_KEY"
        # Your deployment commands go here
